// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5gX0AwtVMcsqlI_vrCCLxq-cqXhxyPJE',
    appId: '1:698798091910:web:d7bbfe561a5f5db0ab2b07',
    messagingSenderId: '698798091910',
    projectId: 'ezprice-1ea63',
    authDomain: 'ezprice-1ea63.firebaseapp.com',
    storageBucket: 'ezprice-1ea63.appspot.com',
    measurementId: 'G-M8E1C8NEFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8h1kRevN_Rx_uyyG1FV3W-WH_jij-q5U',
    appId: '1:698798091910:android:84327d6b5060b2e5ab2b07',
    messagingSenderId: '698798091910',
    projectId: 'ezprice-1ea63',
    storageBucket: 'ezprice-1ea63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLCc3vmNOjF_v-mK-EJzVd3TYELR862PY',
    appId: '1:698798091910:ios:187ce1a55a7c2cacab2b07',
    messagingSenderId: '698798091910',
    projectId: 'ezprice-1ea63',
    storageBucket: 'ezprice-1ea63.appspot.com',
    iosClientId: '698798091910-n6u7hc47e5km7p2iedm7pgj3qolma764.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezprice',
  );
}
